config/routes.rb
Rails.application.routes.draw do
  
  get 'products/index'
  devise_for :users
  root 'pages#index'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index

  end
    def new 
  	@product = Product.new
  end
  def create
@product = current_user.product.build(product_params)
if @product.save
redirect_to root_path
end
end

def show
@product = Product.find_by(id:params[:id])
end

def edit
@product = Product.find_by(id:params[:id])

end

def update
@product = Product.find_by(id:params[:id])

if @product.update(product_params)
redirect_to root_path
end
end

def destroy
@product = Product.find_by(id:params[:id])

@product.destroy
redirect_to root_path
end

private
def post_params
params.require(:product).permit(:user_id,:title,:description, :price)
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
edit.html.erb

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<p>
<% if !user_signed_in? %>
<%= link_to “Login or register”, new_user_session_path %><br>
<% end %>
<% if user_signed_in? %>
<%= link_to “Log out”, destroy_user_session_path, method: :delete %>
<% end %>
</p>
<% if user_signed_in? %>
<%= link_to “New product”, new_product_path %><hr>
<% end %>
<% if @posts == [] %>
<p>No product</p>
<% else %>
<% @product.each do | p | %>
<p>User <b><%= p.user.email %></b> write: <br/>
<%= p.title %><br/>
<%= p.description %><br/>
<%= p.price %><br/></p>
<p><%= link_to “Read more”, product_path(product.id) %></p>
<hr>
<% end %>
<% end %>

app/views/pages/new.html.erb
new.html.erb

app/views/pages/show.html.erb
show.html.erb

app/views/products/edit.html.erb
edit.html.erb

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.html.erb
new.html.erb

app/views/products/show.html.erb
show.html.erb

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>